Address: localhost:8080


Storage:
  # the path to the repository
  StoragePath: ./storage

  # without slashes
  StorageDataFileFormat: json
  
  # the name of the data file inside the storage
  StorageDataFile: tires1.json


  # the path to the image storage inside the storage
  StorageImages: tires-img
